#!/usr/bin/env bash
# deploy.sh - Deploy the Password Manager application.
#
# Usage:
#   ./deploy.sh dev          # Local development (generates secrets, starts Docker)
#   ./deploy.sh prod         # Production (requires pre-set env vars or .env files)
#   ./deploy.sh secrets      # Generate secrets only (for dev or prod)
#   ./deploy.sh seed         # Seed the database (create admin user + default groups)
#
# For production, secrets must be provided via:
#   1. Environment variables (DATABASE_URL, ENCRYPTION_KEY, POSTGRES_PASSWORD)
#   2. .env.db and .env.backend files (git-ignored)
#   3. Docker secrets at /run/secrets/ (injected by Docker runtime)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ─── Colors ─────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1" >&2; }

# ─── Usage ──────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $0 <command>

Commands:
  dev       Start local development environment (generates secrets if missing)
  prod      Start production environment (requires pre-configured secrets)
  secrets   Generate random secrets and write them to backend/secrets/*.txt
  seed      Initialize the database (create admin user + default groups)
  clean     Remove generated files (.env.*, backend/secrets/*.txt, encryption_key)

For production deployment, secrets must be provided via one of:
  1. Environment variables: DATABASE_URL, ENCRYPTION_KEY, POSTGRES_PASSWORD
  2. .env.db and .env.backend files (git-ignored, generated by this script)
  3. Docker secrets at /run/secrets/ (injected by Docker at runtime)

Examples:
  $0 dev                  # Dev setup + start
  $0 secrets && $0 dev    # Generate secrets first, then start
  $0 prod                 # Production start (secrets pre-configured)
  $0 seed                 # Initialize database after start
EOF
    exit 1
}

# ─── Secret Generation ─────────────────────────────────────────────
generate_secrets() {
    log "Generating secrets..."
    mkdir -p "$SCRIPT_DIR/backend/secrets"

    openssl rand -hex 32 > "$SCRIPT_DIR/backend/secrets/postgres_password.txt"
    log "  postgres_password: $(wc -c < "$SCRIPT_DIR/backend/secrets/postgres_password.txt") bytes hex"

    openssl rand -hex 32 > "$SCRIPT_DIR/backend/secrets/secret_key.txt"
    log "  secret_key (JWT):  $(wc -c < "$SCRIPT_DIR/backend/secrets/secret_key.txt") bytes hex"

    openssl rand -base64 32 > "$SCRIPT_DIR/backend/secrets/encryption_key.txt"
    log "  encryption_key:    $(wc -c < "$SCRIPT_DIR/backend/secrets/encryption_key.txt") bytes base64"
}

# ─── Env File Generation ───────────────────────────────────────────
generate_env_files() {
    local pg_password
    pg_password=$(cat "$SCRIPT_DIR/backend/secrets/postgres_password.txt")
    local enc_key
    enc_key=$(cat "$SCRIPT_DIR/backend/secrets/encryption_key.txt")

    cat > "$SCRIPT_DIR/.env.db" <<EOF
# Local development database configuration
# DO NOT commit this file to version control
POSTGRES_DB=password_manager
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${pg_password}
EOF
    log "  .env.db created"

    cat > "$SCRIPT_DIR/.env.backend" <<EOF
# Local development backend configuration
# DO NOT commit this file to version control
DATABASE_URL=postgresql+asyncpg://postgres:${pg_password}@db:5432/password_manager
ENCRYPTION_KEY=${enc_key}
EOF
    log "  .env.backend created"
}

# ─── Command: dev ───────────────────────────────────────────────────
cmd_dev() {
    log "Starting local development environment..."

    # Generate secrets if they don't exist
    if [ ! -f "$SCRIPT_DIR/backend/secrets/postgres_password.txt" ]; then
        warn "No secrets found. Generating..."
        generate_secrets
    else
        log "Secrets already exist in backend/secrets/"
    fi

    # Generate .env files from secrets
    generate_env_files

    # Check Docker
    if ! command -v docker &>/dev/null || ! docker info &>/dev/null; then
        err "Docker is not running. Please install/start Docker first."
        exit 1
    fi

    # Build and start
    log "Building and starting containers..."
    docker compose up --build -d

    log "Waiting for database to be ready..."
    sleep 5

    # Seed the database
    log "Seeding database (creating admin user + default groups)..."
    docker compose exec backend python seed.py

    log ""
    log "═══════════════════════════════════════════════════════════"
    log "  Password Manager is running!"
    log "  Frontend:  http://localhost:3000"
    log "  Backend:   http://localhost:8000"
    log "  API Docs:  http://localhost:8000/docs"
    log "═══════════════════════════════════════════════════════════"
    log ""
    warn "⚠️  Secrets are stored in:"
    warn "    backend/secrets/*.txt  (git-ignored)"
    warn "    .env.db / .env.backend (git-ignored)"
    warn ""
    warn "⚠️  Back up these files securely. If lost, all encrypted data"
    warn "    becomes unrecoverable."
}

# ─── Command: prod ──────────────────────────────────────────────────
cmd_prod() {
    log "Starting production environment..."

    # Validate secrets are provided
    local missing=0

    if [ -z "${DATABASE_URL:-}" ] && [ ! -f "$SCRIPT_DIR/.env.backend" ]; then
        err "DATABASE_URL not set and .env.backend not found."
        missing=1
    fi

    if [ -z "${ENCRYPTION_KEY:-}" ] && [ ! -f "$SCRIPT_DIR/.env.backend" ]; then
        err "ENCRYPTION_KEY not set and .env.backend not found."
        missing=1
    fi

    if [ -z "${POSTGRES_PASSWORD:-}" ] && [ ! -f "$SCRIPT_DIR/.env.db" ]; then
        err "POSTGRES_PASSWORD not set and .env.db not found."
        missing=1
    fi

    if [ "$missing" -eq 1 ]; then
        cat <<EOF

Provide secrets via one of:
  1. Environment variables:
     export DATABASE_URL=...
     export ENCRYPTION_KEY=...
     export POSTGRES_PASSWORD=...

  2. .env files (git-ignored):
     .env.db   → POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
     .env.backend → DATABASE_URL, ENCRYPTION_KEY

  3. Docker secrets (injected at /run/secrets/ by Docker runtime)

EOF
        exit 1
    fi

    # Generate .env files if env vars are set but files don't exist
    if [ -n "${DATABASE_URL:-}" ] && [ ! -f "$SCRIPT_DIR/.env.backend" ]; then
        cat > "$SCRIPT_DIR/.env.backend" <<EOF
DATABASE_URL=${DATABASE_URL}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
EOF
        log "  .env.backend created from environment variables"
    fi

    if [ -n "${POSTGRES_PASSWORD:-}" ] && [ ! -f "$SCRIPT_DIR/.env.db" ]; then
        cat > "$SCRIPT_DIR/.env.db" <<EOF
POSTGRES_DB=password_manager
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF
        log "  .env.db created from environment variables"
    fi

    # Check Docker
    if ! command -v docker &>/dev/null || ! docker info &>/dev/null; then
        err "Docker is not running. Please install/start Docker first."
        exit 1
    fi

    # Build and start
    log "Building and starting containers..."
    docker compose up --build -d

    log ""
    log "═══════════════════════════════════════════════════════════"
    log "  Production environment started!"
    log "  Backend:   http://localhost:8000"
    log "  API Docs:  http://localhost:8000/docs"
    log "═══════════════════════════════════════════════════════════"
    log ""
    warn "⚠️  Configure a reverse proxy (nginx/Traefik) with TLS for"
    warn "    production. The docker-compose.yml exposes ports without HTTPS."
    warn ""
    warn "⚠️  Secrets must be backed up securely."
}

# ─── Command: secrets ───────────────────────────────────────────────
cmd_secrets() {
    warn "This will overwrite existing secrets in backend/secrets/."
    read -p "Continue? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log "Aborted."
        exit 0
    fi
    generate_secrets
    generate_env_files
    log ""
    log "Secrets generated. .env.db and .env.backend updated."
    warn "⚠️  Back up backend/secrets/*.txt securely."
}

# ─── Command: seed ──────────────────────────────────────────────────
cmd_seed() {
    log "Seeding database..."
    if ! docker compose ps backend &>/dev/null; then
        err "Backend container is not running. Start with '$0 dev' or '$0 prod' first."
        exit 1
    fi
    docker compose exec backend python seed.py
}

# ─── Command: clean ─────────────────────────────────────────────────
cmd_clean() {
    warn "This will remove all generated secrets and env files."
    read -p "Continue? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log "Aborted."
        exit 0
    fi
    rm -f "$SCRIPT_DIR/.env.db" "$SCRIPT_DIR/.env.backend"
    rm -f "$SCRIPT_DIR/.env.db.bak" "$SCRIPT_DIR/.env.backend.bak"
    rm -rf "$SCRIPT_DIR/backend/secrets/"
    rm -f "$SCRIPT_DIR/backend/.encryption_key"
    rm -f "$SCRIPT_DIR/.encryption_key"
    log "Cleaned. Removed .env.* files and backend/secrets/."
    warn "⚠️  All encrypted data will become unrecoverable if you regenerate."
}

# ─── Main ───────────────────────────────────────────────────────────
case "${1:-help}" in
    dev)      cmd_dev ;;
    prod)     cmd_prod ;;
    secrets)  cmd_secrets ;;
    seed)     cmd_seed ;;
    clean)    cmd_clean ;;
    *)        usage ;;
esac
